name: Publish
on:
  release:
    types: [released]

jobs:
  publish:
    name: Publish
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: read version number
        id: buildnumber
        run: |
          echo ::set-output name=versionName::$(./gradlew -q pV)

      - name: Publish Library
        run: |
          echo "Publishing library🚀"
          ./gradlew publish --no-daemon --no-parallel
          echo "Published✅"
          echo "Releasing repository...🚀"
          ./gradlew closeAndReleaseRepository
          echo "Released✅"
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ steps.buildnumber.outputs.versionName }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
